=== rbuache/SER-Plex/Workspace/OfficeCinema/DTD/critic.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT critics (movie)*>
<!ELEMENT movie (critic)*>
<!ATTLIST movie name CDATA #REQUIRED>
<!ELEMENT critic (content, language, source, date, note)>
<!ATTLIST critic id CDATA #REQUIRED>
<!ELEMENT content (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT note (#PCDATA)>

=== rbuache/SER-Plex/Workspace/OfficeCinema/XML/critic.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="../XSL/Stylesheet.xsl"?>

<!DOCTYPE critics SYSTEM "../DTD/critic.dtd">

<critics>
	<movie name="Transformers">
		<critic id="1">
			<content>THIS MOVIE IS BAD</content>
			<language>English</language>
			<source>Rui</source>
			<date>12.03.2014</date>
			<note>2/5</note>
		</critic>
		<critic id="2">
			<content>THIS MOVIE IS BAD</content>
			<language>English</language>
			<source>Rui</source>
			<date>12.03.2014</date>
			<note>2/5</note>
		</critic>
	</movie>
</critics>
