=== rbuache/SER-Plex/DTD/actor.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT actors (actor)*>
<!ELEMENT actor (name, biography, born, died?, picture*, filmography*)>
<!ELEMENT filmography (movie*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT biography (#PCDATA)>
<!ELEMENT born (#PCDATA)>
<!ELEMENT died (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT movie (#PCDATA)>

=== rbuache/SER-Plex/XML/actor.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="../XSL/Stylesheet.xsl"?>

<!DOCTYPE actors SYSTEM "../DTD/actor.dtd">

<actors>
	<actor>
		<name>Shia LaBeouf</name>
		<biography>Brat Jr., son of Brat Sr. and Bratova. Born in Bratland</biography>
		<born>11.06.1986</born>
		<picture>http://ia.media-imdb.com/images/M/MV5BMTMyNDA0MDI4OV5BMl5BanBnXkFtZTcwMDQzMzEwMw@@._V1_SY317_CR16,0,214,317_.jpg</picture>
		<filmography>
			<movie>Transformers</movie>
			<movie>Transformers 2</movie>
			<movie>Transformers 3</movie>
		</filmography>
	</actor>
</actors>
