=== rbuache/SER-Plex/DTD/critic.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT critics (critic)*>
<!ELEMENT critic (movieName, criticID, content, language, source, date, note)>
<!ELEMENT actor (actorName, role)> <!--role is either "lead" or "secondary"-->
<!ELEMENT movieName (#PCDATA)>
<!ELEMENT criticID (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT note (#PCDATA)>

=== rbuache/SER-Plex/XML/critic.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSL/Stylesheet.xsl"?>
<!DOCTYPE critics SYSTEM "../DTD/critic.dtd">
<critics>
  <movie name="Transformers">
    <critic id="1">
      <content>Film d'action avec des robots</content>
      <language>Fran√ßais</language>
      <source>L'Hebdo</source>
      <date>12.03.2014</date>
      <note>3/5</note>
    </critic>
    <critic id="2">
      <content>This movie is bad</content>
      <language>English</language>
      <source>Rui</source>
      <date>12.03.2014</date>
      <note>2/5</note>
    </critic>
  </movie>
</critics>
