=== rbuache/SER-Plex/DTD/location.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT locations (location)*>
<!ELEMENT location (name, address, tel, rooms*) >
<!ELEMENT room (name,nbSeat)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT nbSeat (#PCDATA)>

=== rbuache/SER-Plex/XML/location.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSL/Stylesheet.xsl"?>
<!DOCTYPE locations SYSTEM "../DTD/location.dtd">
<locations>
  <location>
    <name>Flon</name>
    <address>Route du Flon</address>
    <tel>021/800808</tel>
    <rooms>
      <name>01</name>
      <nbSeat>220</nbSeat>
    </rooms>
    <rooms>
      <name>02</name>
      <nbSeat>100</nbSeat>
    </rooms>
  </location>
  <location>
    <name>Galerie</name>
    <address>Route du Flon</address>
    <tel>021/800808</tel>
    <rooms>
      <name>01</name>
      <nbSeat>260</nbSeat>
    </rooms>
  </location>
</locations>
