=== rbuache/SER-Plex/DTD/movie.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT movies (movie)*>
<!ELEMENT movie (name, resume, year, director+, actor*, critic*, picture*, genre+, minimumAge)>
<!ELEMENT actor (actorName, role)> <!--role is either "lead" or "secondary"-->
<!ELEMENT name (#PCDATA)>
<!ELEMENT resume (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT minimumAge (#PCDATA)>
<!ELEMENT actorName (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT critic (#PCDATA)>

=== rbuache/SER-Plex/XML/movie.xml
<?xml version="1.0" ?>

<!DOCTYPE movies SYSTEM "../DTD/movie.dtd">

<movies>
	<movie>
		<name>Transformers</name>
		<resume>Decepticons vs Optimus Prime</resume>
		<year>2007</year>
		<director>Michael Bay</director>
		<picture>http://ia.media-imdb.com/images/M/MV5BMTQwNjU5MzUzNl5BMl5BanBnXkFtZTYwMzc1MTI3._V1_SY317_CR0,0,214,317_.jpg</picture>
		<genre>Action</genre>
		<minimumAge>12</minimumAge>
	</movie>
</movies>
