=== rbuache/SER-Plex/DTD/planification.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT planifications (movie)*>
<!ELEMENT movie (name,schedule*)>
<!ELEMENT schedule (location, date, hour)>
<!ELEMENT location (#PCDATA)>
<!ATTLIST location room CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT hour (#PCDATA)>

=== rbuache/SER-Plex/XML/planification.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="../XSL/Stylesheet.xsl"?>

<!DOCTYPE planifications SYSTEM "../DTD/planification.dtd" >

<planifications>
	<movie>
		<name>Transformers</name>
		<schedule>
			<location room="1">Flon</location>
			<date>12.03.2014</date>
			<hour>15.00</hour>
		</schedule>
	</movie>
	<movie>
		<name>Equilibrium</name>
		<schedule>
			<location room="2">Galerie</location>
			<date>12.03.2014</date>
			<hour>17.00</hour>
		</schedule>
	</movie>
	<movie>
		<name>American Outlaws</name>
		<schedule>
			<location room="1">Flon</location>
			<date>12.03.2014</date>
			<hour>18.00</hour>
		</schedule>
	</movie>
</planifications>

=== rbuache/SER-Plex/SER-Plex_Buache_Reis/XML/planification.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSL/Stylesheet.xsl"?>
<!DOCTYPE planifications SYSTEM "../DTD/planification.dtd">
<planifications>
  <movie>
    <name>Equilibrium</name>
    <schedule>
      <location room="2">Galerie</location>
      <date>2014-06-26</date>
      <hour>17.00</hour>
    </schedule>
  </movie>
  <movie>
    <name>American Outlaws</name>
    <schedule>
      <location room="1">Flon</location>
      <date>2014-06-27</date>
      <hour>18.00</hour>
    </schedule>
  </movie>
  <movie>
    <name>Godzilla</name>
    <schedule>
      <location room="4">Flon</location>
      <date>2014-06-25</date>
      <hour>20.00</hour>
    </schedule>
  </movie>
  <movie>
    <name>Neighbors</name>
    <schedule>
      <location room="2">Flon</location>
      <date>2014-06-25</date>
      <hour>18.00</hour>
    </schedule>
  </movie>
  <movie>
    <name>Million Dollar Arm</name>
    <schedule>
      <location room="2">Flon</location>
      <date>2014-06-25</date>
      <hour>16:00</hour>
    </schedule>
  </movie>
</planifications>
